[#ftl]
[@b.head/]
[@b.div id="wechat"]
	[@b.form action="!search" title="ui.searchForm" target="wechatlist" theme="search"]
		[@b.textfields names="wechatAccount.wechatName|wechatNumber;微信名或微信号"/]
	[/@]
	[@b.div href="!search" id="wechatlist" class="dataList"/]
[/@]	
[@b.foot/]
